---
title: "Experience and Qualifications"
output: 
  html_document: 
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---
---

## Education

#### *Methodology and Statistics for the Behavioural, Biomedical and Social Sciences (MSc)*
<font size = "3">
  \| *University of Utrecht & University of Twente, Netherlands* - September 2019 to current.    
  \| Additional Notable Skills: R Coding and Statistical Communication.  
  \| Areas of Interest: Statistical Communication in R & R-markdown and Accessible Data Visualisation.  
  \| Projects: Shiny App Development for a Psychometeric Project (Undeployed).  
  
#### *Psychological Theory and Practice (MSci)*  
  \| *University of Reading, United Kingdom* - September 2015 to May 2019.   
  \| Awarded: First Division, Second Class Honours Degree (2:1).  
  \| Certificates: Low Intensity Psychological Interventions, September 2018.  
  \| Thesis: An Investigation into the Relationship between an Individual’s engagement in Inner speech and Individual differences in Dissociation. (Unpublished).  
  \| Additional Notable Skills: SPSS, fMRI data analysis with FSLView & Shell.  
  \| Areas of Interest: Cognitive, Clinical and Biological Psychology and Research Methods in Psychology.  

---
## Experience
### Employment  
#### *Theatre Sound Councellor*.  
  \| *French Woods Festival of the Performing Arts, USA*.  
  \| Summer Seasons, 2016-2019.  
  \| *Positions Held*: Head of Theatre Sound: 2019; Theatre Sound Councellor: 2016-2018  
  
#### *Student Ambassador*.  
  \| *University of Reading, UK*.  
  \| September 2016 - May 2019.  
  \| *Positions Held*: Student Ambassador: 2017-2019; Open Day Ambassador: 2016-2017  
  
#### *Disabled Students Social Mentor*.  
  \| *University of Reading, UK*.  
  \| September 2017 - May 2019.  
  
#### *Study Smart Ambassador*.   
  \| *University of Reading, UK*.  
  \| September 2017 - December 2018.  
  \| *Positions Held*: Study Smart Ambassador: 2017, Team Leader: 2018.  
  
#### *Trainee Psychological Wellbeing Practitioner*.  
  \| *Oxford Health NHS Foundation Trust, UK*.  
  \| September 2017 - May 2018.  
  \| Traineeship for the Low Intensity Psychological Interventions Certificate, this involved over 80 hours of direct psychological support for clients within the Oxford Health Service.   
  
### Volunteer Experience
  
  